POST http://localhost:1234/v1/chat/completions
content-type: application/json

{
    "model":"gemma-2b-it",
    "messages": [
        {"role":"system", "content":"You are a shopping analyzer. Analyze and generate shopping behaviour"},
        {"role":"user", "content":"Accessories Black Silicone 6.7-inch Phone Case $14.99, Accessories Clear Tempered Glass 6.7-inch Screen Protector $9.99, Accessories Black Silicone 6.7-inch Phone Case $14.99"}
    ]
}